# Template derived from https://developer.okta.com/blog/2020/05/18/travis-ci-to-github-actions#first-steps-to-github-actions

name: Java CI

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8 
      - name: Build with Maven
        run: ./mvnw -B verify 